### Numpy

### Why we use numpy?

- Numpy provides efficient storage.
- It also provide better ways of handling data for processing 
- It is fast.
- It is easy to learn
- Numpy uses relatively less memory to store data.

In [1]:
import numpy as np

In [2]:
# creating array by using numpy
myarr = np.array([1,2,3,4,5])

In [3]:
myarr

array([1, 2, 3, 4, 5])

In [4]:
# creating array with it's dtypes

myarr1 = np.array([12,34,56,78,9],np.int32)

In [5]:
myarr1[3]

78

In [6]:
type(myarr1)

numpy.ndarray

In [7]:
myarr1.shape

(5,)

In [8]:
myarr1.dtype

dtype('int32')

In [9]:
## TO find numpy type search - numpy type reference

In [10]:
# Create two dimension array
myarr2 = np.array([[23,34,55,67,88,45,76,345,66]])

In [11]:
myarr2[0,3]

67

In [12]:
#Change existing element value of array
myarr2[0,3] = 103

In [13]:
myarr2[0,3]

103

In [14]:
myarr2

array([[ 23,  34,  55, 103,  88,  45,  76, 345,  66]])

### Array Creation Method

#### There are 5 general mechanisms for creating arrays:

 - Conversion from other Python structures (e.g., lists, tuples)
 - Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)
 - Reading arrays from disk, either from standard or custom formats
 - Creating arrays from raw bytes through the use of strings or buffers
 - Use of special library functions (e.g., random)


#### Conversion from other Python structures (e.g., lists, tuples)

In [15]:
listarray = np.array([[1,2,3],[5,8,4],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 4],
       [0, 3, 1]])

In [16]:
listarray.dtype

dtype('int32')

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [19]:
# Also create object type array by using numpy and dictionary

np.array({33,2,45,23})

array({33, 2, 45, 23}, dtype=object)

#### Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)

In [20]:
zeros = np.zeros([2,5])

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeros.dtype

dtype('float64')

In [23]:
zeros.shape

(2, 5)

In [24]:
arng = np.arange(15)

In [25]:
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
lspace = np.linspace(1,50,10)

In [27]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [28]:
emp = np.empty((4,6))

In [29]:
emp # this is empty array wich select random number for array elements

array([[6.23042070e-307, 2.89275220e-307, 1.78022342e-306,
        9.34577196e-307, 1.24610383e-306, 1.69118108e-306],
       [8.06632139e-308, 1.20160711e-306, 1.69119330e-306,
        1.29062229e-306, 8.45590539e-307, 6.23054972e-307],
       [1.24612081e-306, 1.60218491e-306, 6.89813978e-307,
        1.78021527e-306, 1.42418172e-306, 8.06609645e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 1.11261162e-306, 1.78021527e-306]])

In [30]:
emp_like = np.empty_like(lspace)

In [31]:
emp_like # first it create empty array with assign array size and then used it's value

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [32]:
# create identity matrix array

ide = np.identity(9)

In [33]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
ide.shape

(9, 9)

In [35]:
arr = np.arange(99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
# now convert this array into 2 dimentional array by using reshape()
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
# but arr array is not changed
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
#so we want to change that arr use following techqiue
arr = arr.reshape(3,33)

In [40]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
#Now we want make arr array in it's previous shape(i.e 99 contionus elements or one dimentional)
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.shape # so it's not change the shape do next thing

(3, 33)

In [43]:
arr = arr.ravel()

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
arr.shape

(99,)

### Numpy Axis
- In two dimension array row represent by axis0 and column represent by axis1.
- In One dimension array there are only one axis i.e axis0

In [46]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [47]:
ar = np.array(x)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.sum(axis = 0)

array([12,  8,  9])

In [50]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [51]:
# Tranpose the array
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [52]:
# convert array into iterator
ar.flat

In [53]:
type(ar)

numpy.ndarray

In [54]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [55]:
# to 
ar.ndim

2

In [56]:
ar.size #size of array

9

In [57]:
ar.nbytes # to total bytes consume by our array 

36

In [58]:
# Creating one dimensional array
oneDim = np.array([1,2,45,666,34])

In [59]:
oneDim.argmax() # it's given maximum value index from array 

3

In [60]:
oneDim.argmin() # it's given minimum value index from array 

0

In [61]:
oneDim.argsort() # it's give sorting index of array (not a sorting value of array)

array([0, 1, 4, 2, 3], dtype=int64)

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [63]:
ar.argmin()

8

In [64]:
ar.argmax()

6

In [65]:
ar.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [66]:
ar.argmin(axis = 0)

array([0, 2, 2], dtype=int64)

In [67]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [68]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [69]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

### Matrix Calculation

In [70]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [71]:
ar2 = np.array([[1,2,1],
              [4,0,6],
              [8,1,0]])

In [72]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [73]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [74]:
# In list it not possible
[23,34]+[33,45]

[23, 34, 33, 45]

In [75]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [76]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [77]:
ar.sum()

29

In [78]:
ar.min()

0

In [79]:
ar.max()

7

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [81]:
# To find the element from array
np.where(ar > 5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [82]:
type(np.where(ar > 5))

tuple

In [83]:
np.count_nonzero(ar)

8

In [84]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [85]:
ar[1,2] = 0

In [86]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

### Checking size of numpy array and compare with python

In [87]:
import sys

In [88]:
py_ar = [12,33,44,55]

In [89]:
np_ar = np.array(py_ar)

In [90]:
sys.getsizeof(1)*len(py_ar)

112

In [91]:
np_ar.itemsize * np_ar.size

16

In [92]:
np_ar.tolist()

[12, 33, 44, 55]

In [93]:
### Numpy Documentation:- 